name: tictactoe
description: "The famous game of Tic Tac Toe"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  gap: ^3.0.1
  shared_preferences: ^2.5.3
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.3
  custom_lint: ^0.8.1

flutter:
  generate: true
  uses-material-design: true
